version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_HOST: "%"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
